---
- hosts: processing-cluster-zookeepers
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  pre_tasks:
    - service: name=monit state=stopped
      become: yes
      ignore_errors: true
  become: yes
  roles:
    - jdk-1.8.0_121
    - zookeeper-upgrade
  post_tasks:
    - service: name=monit state=started
      become: yes
      ignore_errors: true
